# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/Z7_Zynq_base/Z7_Zynq_base.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Z7_Zynq_base || ORIG_REF_NAME==Z7_Zynq_base} -quiet] -quiet

# IP: bd/Z7_Zynq_base/ip/Z7_Zynq_base_processing_system7_0_0/Z7_Zynq_base_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Z7_Zynq_base_processing_system7_0_0 || ORIG_REF_NAME==Z7_Zynq_base_processing_system7_0_0} -quiet] -quiet

# IP: bd/Z7_Zynq_base/ip/Z7_Zynq_base_clk_wiz_0_0/Z7_Zynq_base_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Z7_Zynq_base_clk_wiz_0_0 || ORIG_REF_NAME==Z7_Zynq_base_clk_wiz_0_0} -quiet] -quiet

# IP: bd/Z7_Zynq_base/ip/Z7_Zynq_base_axi_gpio_0_0/Z7_Zynq_base_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Z7_Zynq_base_axi_gpio_0_0 || ORIG_REF_NAME==Z7_Zynq_base_axi_gpio_0_0} -quiet] -quiet

# IP: bd/Z7_Zynq_base/ip/Z7_Zynq_base_axi_gpio_1_0/Z7_Zynq_base_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Z7_Zynq_base_axi_gpio_1_0 || ORIG_REF_NAME==Z7_Zynq_base_axi_gpio_1_0} -quiet] -quiet

# IP: bd/Z7_Zynq_base/ip/Z7_Zynq_base_axi_iic_0_0/Z7_Zynq_base_axi_iic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Z7_Zynq_base_axi_iic_0_0 || ORIG_REF_NAME==Z7_Zynq_base_axi_iic_0_0} -quiet] -quiet

# IP: bd/Z7_Zynq_base/ip/Z7_Zynq_base_axi_quad_spi_0_0/Z7_Zynq_base_axi_quad_spi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Z7_Zynq_base_axi_quad_spi_0_0 || ORIG_REF_NAME==Z7_Zynq_base_axi_quad_spi_0_0} -quiet] -quiet

# IP: bd/Z7_Zynq_base/ip/Z7_Zynq_base_axi_gpio_2_0/Z7_Zynq_base_axi_gpio_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Z7_Zynq_base_axi_gpio_2_0 || ORIG_REF_NAME==Z7_Zynq_base_axi_gpio_2_0} -quiet] -quiet

# IP: bd/Z7_Zynq_base/ip/Z7_Zynq_base_xbar_0/Z7_Zynq_base_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Z7_Zynq_base_xbar_0 || ORIG_REF_NAME==Z7_Zynq_base_xbar_0} -quiet] -quiet

# IP: bd/Z7_Zynq_base/ip/Z7_Zynq_base_auto_pc_0/Z7_Zynq_base_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Z7_Zynq_base_auto_pc_0 || ORIG_REF_NAME==Z7_Zynq_base_auto_pc_0} -quiet] -quiet

# IP: bd/Z7_Zynq_base/ip/Z7_Zynq_base_ps7_0_axi_periph_0/Z7_Zynq_base_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Z7_Zynq_base_ps7_0_axi_periph_0 || ORIG_REF_NAME==Z7_Zynq_base_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/Z7_Zynq_base/ip/Z7_Zynq_base_rst_ps7_0_100M_0/Z7_Zynq_base_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Z7_Zynq_base_rst_ps7_0_100M_0 || ORIG_REF_NAME==Z7_Zynq_base_rst_ps7_0_100M_0} -quiet] -quiet

# XDC: c:/Users/roger.dickerson/Projects/Xilinx/workspace/Platform_0709_Base_Z7/Platform_0709_Base_Z7.gen/sources_1/bd/Z7_Zynq_base/Z7_Zynq_base_ooc.xdc
