# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/roger.dickerson/Projects/Xilinx/workspace/Platform_0709_Base_Z7/Platform_0709_Base_Z7.srcs/sources_1/bd/Z7_Zynq_base/ip/Z7_Zynq_base_auto_pc_0/Z7_Zynq_base_auto_pc_0.xci
# IP: The module: 'Z7_Zynq_base_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/roger.dickerson/Projects/Xilinx/workspace/Platform_0709_Base_Z7/Platform_0709_Base_Z7.gen/sources_1/bd/Z7_Zynq_base/ip/Z7_Zynq_base_auto_pc_0/Z7_Zynq_base_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Z7_Zynq_base_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/roger.dickerson/Projects/Xilinx/workspace/Platform_0709_Base_Z7/Platform_0709_Base_Z7.srcs/sources_1/bd/Z7_Zynq_base/ip/Z7_Zynq_base_auto_pc_0/Z7_Zynq_base_auto_pc_0.xci
# IP: The module: 'Z7_Zynq_base_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/roger.dickerson/Projects/Xilinx/workspace/Platform_0709_Base_Z7/Platform_0709_Base_Z7.gen/sources_1/bd/Z7_Zynq_base/ip/Z7_Zynq_base_auto_pc_0/Z7_Zynq_base_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Z7_Zynq_base_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
