# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/roger.dickerson/Projects/Xilinx/workspace/Platform_0701_Z7/Platform_0701_Z7.srcs/sources_1/bd/Z7_CPU_0/ip/Z7_CPU_0_axi_quad_spi_0_0/Z7_CPU_0_axi_quad_spi_0_0.xci
# IP: The module: 'Z7_CPU_0_axi_quad_spi_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/roger.dickerson/Projects/Xilinx/workspace/Platform_0701_Z7/Platform_0701_Z7.gen/sources_1/bd/Z7_CPU_0/ip/Z7_CPU_0_axi_quad_spi_0_0/Z7_CPU_0_axi_quad_spi_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Z7_CPU_0_axi_quad_spi_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/roger.dickerson/Projects/Xilinx/workspace/Platform_0701_Z7/Platform_0701_Z7.gen/sources_1/bd/Z7_CPU_0/ip/Z7_CPU_0_axi_quad_spi_0_0/Z7_CPU_0_axi_quad_spi_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Z7_CPU_0_axi_quad_spi_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/roger.dickerson/Projects/Xilinx/workspace/Platform_0701_Z7/Platform_0701_Z7.gen/sources_1/bd/Z7_CPU_0/ip/Z7_CPU_0_axi_quad_spi_0_0/Z7_CPU_0_axi_quad_spi_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Z7_CPU_0_axi_quad_spi_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/roger.dickerson/Projects/Xilinx/workspace/Platform_0701_Z7/Platform_0701_Z7.gen/sources_1/bd/Z7_CPU_0/ip/Z7_CPU_0_axi_quad_spi_0_0/Z7_CPU_0_axi_quad_spi_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'Z7_CPU_0_axi_quad_spi_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/roger.dickerson/Projects/Xilinx/workspace/Platform_0701_Z7/Platform_0701_Z7.srcs/sources_1/bd/Z7_CPU_0/ip/Z7_CPU_0_axi_quad_spi_0_0/Z7_CPU_0_axi_quad_spi_0_0.xci
# IP: The module: 'Z7_CPU_0_axi_quad_spi_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/roger.dickerson/Projects/Xilinx/workspace/Platform_0701_Z7/Platform_0701_Z7.gen/sources_1/bd/Z7_CPU_0/ip/Z7_CPU_0_axi_quad_spi_0_0/Z7_CPU_0_axi_quad_spi_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Z7_CPU_0_axi_quad_spi_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/roger.dickerson/Projects/Xilinx/workspace/Platform_0701_Z7/Platform_0701_Z7.gen/sources_1/bd/Z7_CPU_0/ip/Z7_CPU_0_axi_quad_spi_0_0/Z7_CPU_0_axi_quad_spi_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Z7_CPU_0_axi_quad_spi_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/roger.dickerson/Projects/Xilinx/workspace/Platform_0701_Z7/Platform_0701_Z7.gen/sources_1/bd/Z7_CPU_0/ip/Z7_CPU_0_axi_quad_spi_0_0/Z7_CPU_0_axi_quad_spi_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Z7_CPU_0_axi_quad_spi_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/roger.dickerson/Projects/Xilinx/workspace/Platform_0701_Z7/Platform_0701_Z7.gen/sources_1/bd/Z7_CPU_0/ip/Z7_CPU_0_axi_quad_spi_0_0/Z7_CPU_0_axi_quad_spi_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'Z7_CPU_0_axi_quad_spi_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
